qrapp/urls.py
from django.urls import path
from . import views

app_name = 'qrapp'

urlpatterns = [
    path('', views.inicio, name='inicio'),
    path('<str:prm>/', views.index, name='index'),
]

handler404 = "qrapp.views.manejar_not_found"

qrsite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('qr/',include('qrapp.urls', namespace="qr")),
    path('admin/', admin.site.urls),
]

qrapp/models.py
from django.db import models

# Create your models here.

class Empleado(models.Model):
    ide = models.PositiveSmallIntegerField()
    id_of = models.CharField(max_length=10)
    paterno = models.CharField(max_length=50)
    materno = models.CharField(max_length=50)
    nombre = models.CharField(max_length=50)
    descripcion_puesto = models.CharField(max_length=50)
    descripcion_nivel_puesto = models.CharField(max_length=100)
    descripcion_nivel = models.CharField(max_length=100)
    #fecha_creacion = models.DateTimeField(auto_now=True)
    #ultima_act = models.DateTimeField(auto_now=True)

    def __str__(self):
        return '{}'.format(self.nombre)

qrapp/views.py
from django.shortcuts import render
from django.template import loader
from django.http import HttpResponse
from django.urls import reverse_lazy
from .models import Empleado
import datetime

# Create your views here.
def inicio(request):
    template = loader.get_template('inicio.html')
    context = {
        None: None,
    }
    return HttpResponse(template.render(context, request))

def index(request, prm):
    try:
        empleado = Empleado.objects.get(id_of = prm)
        template = loader.get_template('index.html')
        fecha_actual = datetime.datetime.now()
        context = {
            "id_of": empleado.id_of,
            "nombre": empleado.nombre,
            "paterno": empleado.paterno,
            "materno": empleado.materno,
            "descripcion_puesto": empleado.descripcion_puesto,
            "descripcion_nivel": empleado.descripcion_nivel,
            "fecha": fecha_actual,
        }
    except Empleado.DoesNotExist:
        template = loader.get_template('noidentificado.html')
        context = {
            None: None,
        }
    return HttpResponse(template.render(context, request))

def noidentificado(request):
    template = loader.get_template('noidentificado.html')
    context = {
        None: None,
    }
    return HttpResponse(template.render(context, request))

def manejar_not_found(request, exception):
    return render(request, '404.html')

qrapp/templates/base/base.html
<!DOCTYPE html>
<html lang="es">
<head>
  <meta charset="UTF-8">
  {% load static %}
  {% block css %}
    <!--Import Google Icon Font-->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <!-- Compiled and minified CSS -->
    <link type="text/css" rel="stylesheet" href="{% static 'qrapp/css/materialize.min.css' %}" media="screen,projection"/>
    <!--Let browser know website is optimized for mobile-->
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  {% endblock css %}
  {% block title %}
    <title> DIRECCIÓN DE RECURSOS HUMANOS - H. AYUNTAMIENTO DE MORELIA </title>
    <!-- <link rel="shortcut icon" type="image/png" href="{% static 'printexapp/imagenes/favicon.ico' %}"/> -->
  {% endblock %}
  {% block head %}
    <!-- ################  Cabecera de la BASE general ####################-->
    <div class="blue darken-3">
      <div class="row">
        <div class="col s12"></div>
      </div>
      <div class="row">
        <div class="col s1 m1">
        </div>
        <div class="col s5 m5">
          <a href="{% url 'qrapp:inicio' %}" class="brand-logo"><img class="responsive-img" style="width:190px;height:100%;" alt="" src="{% static 'qrapp/imagenes/logo_ayuntamiento_blanco.png' %}"></a>
        </div>
        <div class="col s3 m3">
        </div>
        <div class="col s3 m2">
          <a href="https://www.morelia.gob.mx" target="_blank" class="brand-logo"><img class="responsive-img" style="width:80px;height:100%;" alt="" src="{% static 'qrapp/imagenes/logo_morelia_brilla_blanco.png' %}"></a>
        </div>
        <div class="col s1 m1"></div>
      </div>
    </div>
<!-- ###################################################### -->

{% endblock %}

</head>
<body>
  {% block presentacion %}
  {% endblock %}

  {% block content %}
  {% endblock %}

  {% block footer %}
    <div class="row"></div>
    <div class="white">
      <div class="container">
        <div class="row">
          <!--<div class="white-text">
          <div class="col s12">
            <a href="https://www.morelia.gob.mx">Inicio</a>
              &nbsp;||&nbsp;<a href="{% url 'qrapp:inicio' %}">
              Aviso de Privacidad</a>
            </p>
          -->
            <div class="col s2"></div>
            <div class="col s8">
              <img class="responsive-img" style="width:1000%;height:100%;" alt="" src="{% static 'qrapp/imagenes/barra_colores.png' %}">
            </div>
            </div>
            <div class="col s2"></div>
          </div>
          <div class="row"></div>
          </div>
        </div>
      </div>
    </div>
  {% endblock %}
  {% block javascript %}
  <!-- Compiled and minified JavaScript  -->
  <script>


  </script>

  <!--JavaScript at end of body for optimized loading-->
  <script type="text/javascript" src="{% static 'qrapp/js/materialize.min.js' %}"></script>
{% endblock javascript %}
{% block js %}
{% endblock %}
</body>
</html>

qrapp/templates/index.html
{% extends 'base/base.html' %}
{% block content %}
<div class="container">
  <div class="row">
    <div class="col s12"><h6 class="center-align"> DIRECCIÓN DE RECURSOS HUMANOS</h6></div>
  </div>
  <div class="divider"></div>
  <div class="section">
    <!-- <div class="col s12 "> ID: {{id_of}}</div> -->
    <div class="col s12 "> {{fecha}}</div>
    <div class="col s12"><h4 class="center-align"> {{nombre}} </h4></div>
    <div class="col s12"><h5 class="center-align"> {{paterno}} {{materno}} </h5></div>
    <div class="row"><p> </p></div>
    <div class="col s12"><h6 class="center-align"> <i>PUESTO:</i> <b>{{descripcion_puesto}}</b> </h6></div>
    <div class="col s12"><h6 class="center-align"> <i>ÁREA:</i> <b>{{descripcion_nivel}}</b> </h6></div>
  </div>
  <div class="divider"></div>
  <div class="section"></div>
  <div class="row">
    <div class="col s12"><h6 class="center-align"> </h6></div>
  </div>
</div>

{% endblock %}

qrapp/templates/inicio.html
{% extends 'base/base.html' %}
{% block content %}
<div class="container">
  <div class="divider"></div>
  <div class="section">
    <div class="row">
      <div class="grey-text">
        <div class="col s12"><h6 class="center-align"> Datos no válidos </h6></div>
      </div>
    </div>
  </div>
  <div class="divider"></div>
  <div class="section"></div>
</div>
{% endblock %}

qrapp/templates/noidentificado.html
{% extends 'base/base.html' %}
{% block content %}
<div class="container">
  <div class="divider"></div>
  <div class="section">
    <div class="row">
      <div class="grey-text">
        <div class="col s12"><h6 class="center-align"> Información no encontrada </h6></div>
      </div>
    </div>
  </div>
  <div class="divider"></div>
  <div class="section"></div>
</div>
{% endblock %}

qrapp/templates/qr_delete.html
{% extends 'base/base.html' %}

{% block content %}
<h5> Contenido de ENCUESTA DELETE </h5>
<form method="post">
    {% csrf_token %}
    <h3>¿Desea eliminar el registro de {{ object.nombre }}?</h3>
    <button type="submit">Sí, eliminar</button>
    <a href="{% url 'qr:qr_list' %}">Cancelar</a>
</form>
{% endblock %}

qrapp/templates/qr_form.html
{% extends 'base/base.html' %}

{% block content %}
<h5> Contenido de Qr FORM </h5>
<form method="post">
    {% csrf_token %}
    {{ form.as_p}}
    <a href="{% url 'qr:qr_crear' %}">Limpiar datos</a>
    <button type="submit" name="action">Guardar</button>
</form>
{% endblock %}

qrapp/templates/qr_list.html
{% extends 'base/base.html' %}
{% block content %}

  <table class="table table-bordered">
    <thead>
      <tr>
        <td>Folio</td>
        <td>Nombre</td>
        <td>Fecha</td>
        <td>Activa</td>
        <td>Creada</td>
        <td>Actualizada</td>
        <td>Creador</td>
        <td>Acciones</td>
      </tr>
    </thead>
    <tbody>
      {% if qr %}

      {% for enc in qr %}
      <tr>
        <td>{{ enc.folio }}</td>
        <td>{{ enc.nombre }}</td>
        <td>{{ enc.fecha }}</td>
        <td>{{ enc.activa }}</td>
        <td>{{ enc.fecha_creacion }}</td>
        <td>{{ enc.ultima_act }}</td>
        <td>{{ enc.usuario }}</td>
        <td>
          <a href="{% url 'qr:qr_editar' enc.folio %}">Editar</a>
          <a href="{% url 'qr:qr_borrar' enc.folio %}">Borrar</a>
        </td>
      </tr>
      {% endfor %}
      {% else %}
      <h4> No existen registros de usuarios</h4>
      {%  endif %}
  </tbody>
{% endblock %}

qrapp/templates/usuario_delete.html
{% extends 'base/base.html' %}

{% block content %}
<h5> Contenido de USUARIO DELETE </h5>
<form method="post">
    {% csrf_token %}
    <h3>¿Desea eliminar el registro de {{ object.nombre }}?</h3>
    <button type="submit">Sí, eliminar</button>
    <a href="{% url 'qr:usuario_list' %}">Cancelar</a>
</form>
{% endblock %}

qrapp/templates/usuario_form.html
{% extends 'base/base.html' %}

{% block content %}
<h5> Contenido de Usuario FORM </h5>
<form method="post">
    {% csrf_token %}
    {{ form.as_p}}
    <a href="{% url 'qr:usuario_crear' %}">Limpiar datos</a>
    <button type="submit" name="action">Guardar</button>
</form>
{% endblock %}

qrapp/templates/usuario_list.html
{% extends 'base/base.html' %}
{% block content %}

  <table class="table table-bordered">
    <thead>
      <tr>
        <td>#</td>
        <td>Nombre</td>
        <td>Edad</td>
        <td>Grado</td>
        <td>Corre electrónico</td>
        <td>Fecha de creación</td>
        <td>Ultima actualización</td>
        <td>Acciones</td>
      </tr>
    </thead>
    <tbody>
      {% if usuario %}

      {% for user in usuario %}
      <tr>
        <td>{{ user.id }}</td>
        <td>{{ user.nombre }}</td>
        <td>{{ user.edad }}</td>
        <td>{{ user.grado }}</td>
        <td>{{ user.correo }}</td>
        <td>{{ user.fecha_creacion }}</td>
        <td>{{ user.ultima_act }}</td>
        <td>
          <a href="{% url 'qr:usuario_editar' user.id %}">Editar</a>
          <a href="{% url 'qr:usuario_borrar' user.id %}">Borrar</a>
        </td>
      </tr>
      {% endfor %}
      {% else %}
      <h4> No existen registros de usuarios</h4>
      {%  endif %}
  </tbody>
{% endblock %}